flags: {}
packages:
- '.'
- location:
    git: git@github.com:BlairArchibald/HdpH.git
    commit: 1ff5954385a5190553e3e4070cab5cce714867dc
  subdirs:
  - hdph
  - hdph-closure
- location:
    git: git@github.com:haskell-distributed/network-transport-tcp.git
    commit: c2a316dc93a6d666e5cae61d5676f6a3ec5a7f83
- location:
    git: git@github.com:BlairArchibald/bones.git
    commit: 74c6df0df99ba30767c0c4a977638302d21b18b7
- location:
    git: git@github.com:BlairArchibald/bitSetArray.git
    commit: 7382e2b9314c952d35e3196b85acd62ded7768fc

extra-deps: []
resolver: lts-3.9
